In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_excel("C:\\Users\\zaids\\Downloads\\PAN+Card+Validation+in+PYTHON+-+Scripts\\PAN Card Validation in PYTHON - Scripts\\PAN Number Validation Dataset.xlsx")

In [7]:
df.head()

  Pan_Numbers
0  VGLOD3180G
1  PHOXD7232L
2  MGEPH6532A
3  JJCHK4574O
4  XTQIJ2330L

In [8]:
df.shape

(10000, 1)

In [ ]:
df.describe() # from here itself we can see there are missing values and duplicates in the dataset

        Pan_Numbers
count          9035
unique         9027
top     JVPYR52307F
freq              4

In [13]:
df.isnull().sum()

Pan_Numbers    965
dtype: int64

In [18]:
# simply drop the rows with missing values
df.dropna(inplace = True)

In [19]:
df.isna().sum()

Pan_Numbers    0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(8)

In [21]:
df[df.duplicated(keep = False)].sort_values(by=df.columns.tolist()) # what keep = false does is it shows all the duplicated rows instead of just one of them.

      Pan_Numbers
5201  BPWVM28815K
5202  BPWVM28815K
5191   IPSLX475!I
5192   IPSLX475!I
5342  JVPYR52307F
5344  JVPYR52307F
5345  JVPYR52307F
5346  JVPYR52307F
5188      XTP0675
5189      XTP0675
5318   XVATX221!N
5320   XVATX221!N
5321   XVATX221!N

In [22]:
df.drop_duplicates(inplace = True)

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.shape

(9027, 1)

In [28]:
# handling leading and trailing spaces in the dataset

 # do i need to assign this back to the column? yes i do, otherwise it will not be reflected in the dataset
df['Pan_Numbers'] = df['Pan_Numbers'].apply(lambda x: x.strip())

df.head()

  Pan_Numbers
0  VGLOD3180G
1  PHOXD7232L
2  MGEPH6532A
3  JJCHK4574O
4  XTQIJ2330L

In [29]:
# now all the values should be in uppercase
df['Pan_Numbers'] = df['Pan_Numbers'].apply(lambda x: x.upper())

In [32]:
df.sample(20)

      Pan_Numbers
1428   SCFAL2875S
5602      GHI2115
4985   FDWYC8912I
5335   HALQN135!J
2413   LMMFI3579X
7776   GELO33106G
7739   AQCMW795!E
3962   SUKCU6446F
516    GMGCC3477B
3633   FLSCH6082O
515    XRXPX1022Y
6606      HWQ1744
5029   GHYH33227H
1951   TLCGS8748W
4374   VHOZZ7887T
5313   TCVVZ406!Z
6007  DUVSS92156O
3084   KSLAS0132N
3093   WHYGC7386T
7525      YVG9211

In [ ]:
import re

def is_sequential(s):
    return (
        all(ord(s[i]) + 1 == ord(s[i+1]) for i in range(len(s)-1)) or
        all(ord(s[i]) - 1 == ord(s[i+1]) for i in range(len(s)-1))
    ) # this checks if the characters are in sequential order either increasing or decreasing by comparing the ASCII values of the characters

def has_adjacent_duplicates(s):
    return any(s[i] == s[i+1] for i in range(len(s)-1)) # this checks if there are any adjacent characters that are the same

def validate_pan(pan):
    # Basic format check
    if not re.match(r'^[A-Z]{5}[0-9]{4}[A-Z]$', pan): # this regex checks if the PAN number has 5 uppercase letters followed by 4 digits and then 1 uppercase letter, why did we use not match? because we want to return false if the format is not correct
        return False
    
    first_part = pan[:5]
    digits_part = pan[5:9]
    
    # Alphabet checks
    if has_adjacent_duplicates(first_part):
        return False
    if is_sequential(first_part):
        return False
    
    # Digit checks
    if has_adjacent_duplicates(digits_part):
        return False
    if is_sequential(digits_part):
        return False
    
    return True

In [35]:
df['PAN_Category'] = df['Pan_Numbers'].apply(
    lambda x: "Valid PAN" if validate_pan(x) else "Invalid PAN"
)

In [36]:
df.head(10)

  Pan_Numbers PAN_Category
0  VGLOD3180G    Valid PAN
1  PHOXD7232L    Valid PAN
2  MGEPH6532A    Valid PAN
3  JJCHK4574O  Invalid PAN
4  XTQIJ2330L  Invalid PAN
5  HTJYM3835H    Valid PAN
6  YQTAP6661X  Invalid PAN
7  HVOFE5635Y    Valid PAN
8  HYUIJ7902R    Valid PAN
9  IDSMT3429E    Valid PAN

In [37]:
df.tail(10)

      Pan_Numbers PAN_Category
9989  OTFTG69739H  Invalid PAN
9990   VMARS200!O  Invalid PAN
9991   DAAGE741!V  Invalid PAN
9992      IIF8765  Invalid PAN
9993   PZWW53387M  Invalid PAN
9994   ZMVA03025O  Invalid PAN
9995   TNGUY429!V  Invalid PAN
9996   SMMN33673G  Invalid PAN
9998   RLAI69795T  Invalid PAN
9999      YWY2482  Invalid PAN

In [38]:
df['PAN_Category'].value_counts()

PAN_Category
Invalid PAN    5847
Valid PAN      3180
Name: count, dtype: int64